### ISSUE TITLE
Visualise solution

### ISSUE THREAD

**Issue by rhi-ackland** [robertdoanesolomon/software-engineering-projects-pk#10]

**Comment by rhi-ackland** [comment]
Ability to visualise the solution of a model, and to compare two different solutions.

**Comment by tristramwalsh** [comment]
- [ ] I think you'll want/need to add a separate import line of code to `pkmodel/__init__.py` that says `from .visualisation import name-of-graphing-function`, assuming that you place the graphing functions in a file called `pkmodel/visualisation.py`

**Comment by rhi-ackland** [comment]
Visualisation tool to image one model at a time is complete and uploaded to sixtine_functions branch

**Comment by rhi-ackland** [comment]
When we're packaging this we need to make sure to import the function visualise from the file solution.py

**Comment by robertdoanesolomon** [comment]
well done @rhi-ackland amazing job!
