### ISSUE TITLE
Solve ODE

### ISSUE THREAD

**Issue by rhi-ackland** [robertdoanesolomon/software-engineering-projects-pk#11]

**Comment by rhi-ackland** [comment]
Ability to solve for the drug quantity in each compartment over time, given a model and a protocol

**Comment by tristramwalsh** [comment]
Commit 9b667a9 implemented ODE solving, so the Issue is now closed.

**Comment by tristramwalsh** [comment]
Note that this commit 9b667a9 only does a minimal working implementation of ODE solving - it has not yet set up Class-based functionality, just an MVP using function-based solution.
