### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by tristramwalsh** [robertdoanesolomon/software-engineering-projects-pk#4]

**Comment by tristramwalsh** [comment]
First commit of working functions to branch `sixtine-functions` - see file `prototype.py` in commit 9b667a9

**Comment by rhi-ackland** [comment]
Tests written onto Sarah's branch but still have a few issues. The tests aren't finding the functions, think they are set to the parent class but can't find them in the daughter classes? Specifically there is a problem with the init file, need to import from pkmodel IV or SC.
